### PR TITLE
Changed pom to depend on antlr4 directly rather than via Maven plugin…

### PR DESCRIPTION
**Pull request by alankstewart**
…, to avoid bringing in unnecessary Maven dependencies

### CODE REVIEW

**Comment by julianthome** [comment]
Thanks a lot Alan -- I pulled the changes.

**Comment by alankstewart** [comment]
Thanks Julian. I have a few cosmetic changes (consistent formatting and javadoc changes etc) that I'm happy to contribute as well if that's OK with you ?
Regards
Alan

**Comment by julianthome** [comment]
Dear Alan, sure, that would be great! Thanks a lot, and kind regards, Julian

**Comment by alankstewart** [comment]
Thanks again Julian. Before I start, I wanted to check with you on two pieces of code:
1. StringCompiler - the caching of the lexer at https://github.com/julianthome/inmemantlr/blob/master/src/main/java/org/snt/inmemantlr/StringCompiler.java#L186 causes us a lot intermittent test failures probably due to threading issues. We removed that in our first PR, but noticed you put it back. Would it be OK to remove it again? Performance is still  good without it
2. DefaultTreeListener - https://github.com/julianthome/inmemantlr/blob/master/src/main/java/org/snt/inmemantlr/DefaultTreeListener.java#L116 -  the method getNodes() returns this.getNodes()  which appears to an infinite recursion, according to Intellij. Did you mean to return ast.getNodes() ?

Regards 
Alan

**Comment by alankstewart** [comment]
Perhaps for the lexer caching, I can provide an overloaded constructor with a boolean to turn off caching? Rod suggested a factory method, like GenericParser.independentInstance(grammar, name, this). I can add the boolean field to the class, provide another constructor, and call it using the factory and then parse this along to a new overloaded method in StringCompiler. The default behaviour is to cache as you have done

**Pull request merged**
