### PR TITLE
General Performance and Code Style Improvements

### PR DESCRIPTION
**Pull request by havrikov**

### CODE REVIEW

**Comment by julianthome** [comment]
Hallo Nikolas, wow danke dir. Ich gehe den pull request später durch. Das Resultat von appveyor kann man ignorieren. Es wäre super wenn du den master branch nochmal zurück mergen könntest, ich habe dort die `.yml` für appveyor vor ein paar Tagen entfernt.

**Review by julianthome — CHANGES_REQUESTED** [review]
Hi Nikolas, thank you very much for the changes and improvements. There is only one minor issue in the class `GenericParser`. I'd like to keep _only_ the exception message as part of the logged message. I have added a comment below.

**Comment by havrikov** [comment]
The logger logs the class, message, and stacktrace  of the exception if it is passed as the last parameter.  
Or am I missing something?

**Comment by julianthome** [comment]
Yes, that is true, but usually I prefer having the exception message only. Although they are useful for debugging, I always find the stacktraces a bit overwhelming, especially in log messages. Therefore, I just put `e.getMessage()` after the description of the error.

**Pull request merged**
